# coding=utf8
import sys

IMAGE_TAG_COMPANY_CERTIFICATION = 1
IMAGE_TAG_COMPANY_LICENSE = 2
IMAGE_TAG_COMPANY_SAFE = 3
IMAGE_TAG_COMPANY_CREDIT = 4


SEARCH_KEY_TAG_USER = 1
SEARCH_KEY_TAG_TENDRE = 2
SEARCH_KEY_TAG_WIN_BIDDING = 3

FAVORITE_TAG_TENDER = '1'
FAVORITE_TAG_WIN_BIDDING = '2'